### ISSUE TITLE
Broken Graphs

### ISSUE THREAD

**Issue by jysngrcia** [KnoAll/cacti-template#100]
Hi,

Im getting broken graphs on some devices

![image](https://user-images.githubusercontent.com/46915906/83093110-661ce480-a0d1-11ea-8e99-be33ec8aee36.png)

Any advise?

**Comment by KnoAll** [comment]
This would indicate that the poller is not able to connect via SNMP to that device consistently. I would direct you to the cacti forums

**Comment by jysngrcia** [comment]
Im using SNMPv3 on the device, I will try SNMPv2

Thanks, appreciated your reply
