### ISSUE TITLE
Log rotation issue

### ISSUE THREAD

**Issue by XodusMatthewB** [KnoAll/cacti-template#102]
Hello.
When the cacti.log rotates, I get the error "System log file is not available for writing, please enable write access Log: /var/www/html/cacti/log/cacti.log"

File shows:
-rw-r--r--.  1 cacti  apache  498552 Jul 23 07:23 cacti.log

Changing the file to 664 gets me up but I am having to do it with every rotation.  I didn't have the issue with the original ova but it started after doing the in-place upgrade.  I tried upgrading again (now to 1.2.13) but the problem persists.

Thanks for any assistance you can lend!

**Comment by KnoAll** [comment]
have you/can you try running the script with --fix-permissions switch to see if that helps?

**Comment by XodusMatthewB** [comment]
Forgive me if I didn't do it correctly but I ran;
`./cacti-upgrade.sh --fix-permission`
and it completed without any errors.  Not wanting to wait, I renamed cacti.log and when it created a new file, it was the same `-rw-r--r--. 1 cacti apache` permissions.

Let me know if you can think of anything else to try.

**Comment by KnoAll** [comment]
it should be 
`./cacti-upgrade.sh --fix-permissions`

**Comment by XodusMatthewB** [comment]
So doing the above fixed it but after the log rotated again, it did the same thing.  It happened once a few days after the command but I restarted the VM and tried again in case it needed a kick but today I received the error again.  Any other suggestions?

**Comment by KnoAll** [comment]
Interesting, there may be something wrong with the parent folder permissions and the rights to create a new file as a result. I've not seen this be persistent as you are finding.
