### ISSUE TITLE
Problem for PHP

### ISSUE THREAD

**Issue by francoalbarra87** [KnoAll/cacti-template#104]
Hello,
I wanted to consult this problem that I am having with the php specifically and that I am not finishing to understand what happens.
It turns out that it is not raising the cacti, checking in the /var/log/httpd/error_log it returns an error like the memory limit is very low, so I went to check inside the /etc/php.ini file and saw that is set to 800 M, I continued to increase it but it does not stop returning the same error. The only way I see that it works is by setting it to -1 (no limit), but it doesn't seem like a good practice to leave it like that.

The error it returns is:
[Fri Aug 28 12:04:00.826314 2020] [php7:error] [pid 2424] [client 10.100.22.142:56557] PHP Fatal error:  Allowed memory size of 943718400 bytes exhausted (tried to allocate 425984 bytes) in /var/www/html/cacti/include/vendor/gettext/src/Extractors/Mo.php on line 69
[Fri Aug 28 12:04:07.187122 2020] [php7:error] [pid 2425] [client 10.100.22.142:56558] PHP Fatal error:  Allowed memory size of 943718400 bytes exhausted (tried to allocate 425984 bytes) in /var/www/html/cacti/include/vendor/gettext/src/Extractors/Mo.php on line 69

I already apologize for my English
Regards

**Comment by KnoAll** [comment]
PHP issues are well beyond my expertise. I'm afraid you will have to do some web searching to get more assistance
