### ISSUE TITLE
www.kevinnoall.com/blog NOT WORK

### ISSUE THREAD

**Issue by rrgg-it** [KnoAll/cacti-template#108]
Hi Kevin,
your blog: **www.kevinnoall.com/blog** is not reacheable at the moment.
Can you fix it?
Thank-you!

**Comment by KnoAll** [comment]
Thanks for letting me know! The admin panel is working, but not the site!?

**Comment by KnoAll** [comment]
a wordpress plugin was messed up. should be all good now

**Comment by rrgg-it** [comment]
Yes, it works fine now.
