### ISSUE TITLE
1.2.14 OVF timezone change

### ISSUE THREAD

**Issue by mottld** [KnoAll/cacti-template#115]
After installing the latest OVF 1.2.14, I changed the timezone via

timedatectl set-timezone America/New_York

then edited /etc/php.ini and changed:

date.timezone = America/New_York

restarted httpd

After this the graphs no longer update with data. The time in the graphs is correct and any data before the timezone change is correct, but any new data does not graph. There are no errors in the logs. I rebooted the system to restart all services, no change. I then ran ./cacti-upgrade.sh and verified during the upgrade that php and mysql saw the correct timezones.

Is there somplace else the timezone needs to be changed?

**Comment by KnoAll** [comment]
There is not another place that I'm aware of that I recall. I can go through and check though.

**Comment by mottld** [comment]
It turns out the graphs started populating after the difference in timezones. In this case after 3 hours. 

You should think about making your ovf UTC time.

I will close the case.

**Comment by KnoAll** [comment]
Interesting. good to know the changes you made worked.

**Comment by mottld** [comment]
Turns out mysql is still pulling the wrong system timezone information. Looking in cacti->system utilities->Technical Support->Database Settings the variable time_zone was set to PST (Not sure where this is coming from)

logging into mysql and running SELECT @@global.time_zone; i get SYSTEM so it should have been pulling it from the system timezone. I ended up editing /etc/my.cnf and adding the line 

default-time-zone='America/New_York'

restart mysql and all is right with the world now.

**Comment by KnoAll** [comment]
Interesting. I'm not exactly sure where MYSQL would be pulling that from. Seems the SYSTEM setting should prevail there. I'll have to check around. Perhaps I'll add the line you indicated to my.cnf so that it is easier for others to find.

**Comment by KnoAll** [comment]
The MariaDB support docs indicate that the system_time_zone is pulled at OS startup....
https://mariadb.com/kb/en/server-system-variables/#system_time_zone
Did you reboot the system after TZ change? If not this could explain why that value did not update.

**Comment by KnoAll** [comment]
I did some testing and this is indeed the case. the System timezone setting does not take effect until reboot so MYSQL will not pick up the change

**Comment by mottld** [comment]
Yeah I rebooted a few times. I may try a second install. I'll close this ticket and will reopen if I find anything different.
