### ISSUE TITLE
Fresh Install on CentOS 8.2.2004 - Spine installation failed

### ISSUE THREAD

**Issue by Schietb** [KnoAll/cacti-template#117]
Hi,
First of all, thanks a lot for your work ;)
I installed Cacti using your installation script, following the procedure https://github.com/KnoAll/cacti-template/tree/master/install
Everything went fine, but once installed, I noticed that spine was not installed, and when trying to install it manually, I got the following error : "make: *** [Makefile:974: spine.1] Error 1"
Googling a while learned me that it seems to be due to a known MariaDB bug.
Is there anyway a workaround to get spine working ?
OS version is CentOS 8.2.2004 x64
Thanks in advance for your help.

**Comment by KnoAll** [comment]
Hm, I'll have to lab that out. I am not sure I have tested with that version of CentOS8 yet...

Depeding on the size of your planned deployment, you can use the cmd.php instead of Spine

**Comment by KnoAll** [comment]
Also, you may consider that CentOS8 is being end of lifed much earlier than was anticipated. I'm not even sure they will be doing security updates. CentOS7.x will continue through at least 2024

**Comment by KnoAll** [comment]
It seems there was an update in CentOS8 that requires a different way of installing help2man

yum install dnf-plugins-core

And then:

yum config-manager --set-enabled powertools

Or:

yum config-manager --set-enabled PowerTools

once that is done Spine installs as expected.

I'll have to update the script to include this new requirement

**Comment by KnoAll** [comment]
Updated the script to account for this change. It appears there was change in case for PowerTools to powertools that was breaking the install for help2man on Centos8. Added an OR if installing powertools fails. Should work as expected again.

**Comment by Schietb** [comment]
Hi,
Thanks a lot for your quick reaction.
You're really doing a great job with this script !
I'll try a new fresh install immediately ;)
Have a good day.

**Comment by Schietb** [comment]
Here's my feedback :
Fresh install on CentOS 8.2.2004 successfully completed and spine correctly installed ! 👍 
Thanks a lot for your work.
