### ISSUE TITLE
Keep custom themes after upgrade

### ISSUE THREAD

**Issue by Schietb** [KnoAll/cacti-template#122]
Hi,

First of all, thanks a lot for your work and the install/upgrade script.
Could it be possible to adapt the upgrade script in order to keep any custom theme after an upgrade ?
This is not really an issue but a simple request, as I actually manually copy my custom theme into the ~/cacti/include/themes after each upgrade, but it would be useful if it was automated.
Thanks in advance.

**Comment by KnoAll** [comment]
Apologies for the delay in response. I've not used custom themes so had not considered that. I will look at including those in the script.

**Comment by Schietb** [comment]
Thank you so much !
Have good day.

**Comment by KnoAll** [comment]
script updated to copy themes during upgrade process. hope it helps!
