### ISSUE TITLE
CANC CREATE NEW GRAPHS FOLLOWING ERROR

### ISSUE THREAD

**Issue by sergioprado010489** [KnoAll/cacti-template#140]
I have just deployed fresh ova connect correctly via SNMP but not able to create new graphs, following error appears:

![image](https://user-images.githubusercontent.com/22963124/150314591-287d07be-f9fa-4223-80f7-106202d5dab4.png)

![image](https://user-images.githubusercontent.com/22963124/150314654-e94b8e3b-03dc-4f4d-8ffa-0c7ac04a2ac3.png)

**Comment by KnoAll** [comment]
That typically happens when you look at a new graph before the poller has run. If the graphs still do not show you can try running the script again adding the switch --fix-permissions

**Comment by sergioprado010489** [comment]
Hi, Thanks

![image](https://user-images.githubusercontent.com/22963124/150413711-bdf4b50f-2e2e-41bc-a35e-cf2061564287.png)

it worked using different template, from the list above I used at firs CISCO LTR template and it did not work, after I used the in/out 64 bits template. Thanks!!

**Comment by KnoAll** [comment]
As the OVF is working, I suggest you jump into the Cacti specific forums for support.
https://forums.cacti.net/
