### ISSUE TITLE
Smokeping installation on Rocky Linux 9.1

### ISSUE THREAD

**Issue by Schietb** [KnoAll/cacti-template#159]
Hi,
I just installed a brand new Cacti on a Rocky Linux 9.1 server.
All has run successfully, but I now tried to install SmokePing and, even if it seems to install properly, the process ends with the message "Uh-oh. Sorry, unsupported OS Exiting..."
Did I miss something ?

**OS Version :**
Operating System: Rocky Linux 9.1 (Blue Onyx)
     CPE OS Name: cpe:/o:rocky:rocky:9::baseos
          Kernel: Linux 5.14.0-162.18.1.el9_1.x86_64
    Architecture: x86-64
 Hardware Vendor: VMware, Inc.
  Hardware Model: VMware7,1

**Script output :**
 bash <(curl -s https://raw.githubusercontent.com/KnoAll/cacti-template/master/install/smokeping/install-smokeping.sh)
::: Welcome to Kevin's SmokePing install script!
[sudo] password for cacti:
sudo: printinfo: command not found
::: Checking fping version...
::: Upgrading fping...
Cloning into 'fping'...
remote: Enumerating objects: 2764, done.
remote: Counting objects: 100% (162/162), done.
remote: Compressing objects: 100% (89/89), done.
remote: Total 2764 (delta 88), reused 109 (delta 65), pack-reused 2602
Receiving objects: 100% (2764/2764), 960.52 KiB | 4.95 MiB/s, done.
Resolving deltas: 100% (1905/1905), done.
Branch 'master' set up to track remote branch 'master' from 'origin'.
Switched to a new branch 'master'
configure.ac:7: installing './compile'
configure.ac:52: installing './config.guess'
configure.ac:52: installing './config.sub'
configure.ac:53: installing './install-sh'
configure.ac:53: installing './missing'
src/Makefile.am: installing './depcomp'
configure: loading site script /usr/share/config.site
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for netinet/icmp6.h... yes
checking whether SO_TIMESTAMPNS is declared... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports the include directive... yes (GNU style)
checking whether make supports nested variables... yes
checking dependency style of gcc... gcc3
checking whether to enable maintainer-specific portions of Makefiles... no
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking for gcc option to accept ISO C99... none needed
checking for gcc option to accept ISO Standard C... (cached) none needed
checking how to run the C preprocessor... gcc -E
checking for gethostbyname... yes
checking for connect... yes
checking for sigaction... yes
checking for unistd.h... (cached) yes
checking sys/file.h usability... yes
checking sys/file.h presence... yes
checking for sys/file.h... yes
checking for stdlib.h... (cached) yes
checking sys/select.h usability... yes
checking sys/select.h presence... yes
checking for sys/select.h... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating doc/Makefile
config.status: creating src/Makefile
config.status: creating config.h
config.status: executing depfiles commands
make  all-recursive
make[1]: Entering directory '/home/cacti/fping'
Making all in doc
make[2]: Entering directory '/home/cacti/fping/doc'
pod2man  -c "" -s 8 -r "fping" fping.pod >fping.8
make[2]: Leaving directory '/home/cacti/fping/doc'
Making all in src
make[2]: Entering directory '/home/cacti/fping/src'
gcc -DHAVE_CONFIG_H -I. -I..    -Wall -Wextra -Wno-sign-compare -DIPV6 -g -O2 -MT fping-fping.o -MD -MP -MF .deps/fping-fping.Tpo -c -o fping-fping.o `test -f 'fping.c' || echo './'`fping.c
fping.c: In function ‘decode_icmp_ipv4’:
fping.c:2078:12: warning: unused parameter ‘response_addr_len’ [-Wunused-parameter]
 2078 |     size_t response_addr_len,
      |     ~~~~~~~^~~~~~~~~~~~~~~~~
mv -f .deps/fping-fping.Tpo .deps/fping-fping.Po
gcc -DHAVE_CONFIG_H -I. -I..    -Wall -Wextra -Wno-sign-compare -DIPV6 -g -O2 -MT fping-seqmap.o -MD -MP -MF .deps/fping-seqmap.Tpo -c -o fping-seqmap.o `test -f 'seqmap.c' || echo './'`seqmap.c
mv -f .deps/fping-seqmap.Tpo .deps/fping-seqmap.Po
gcc -DHAVE_CONFIG_H -I. -I..    -Wall -Wextra -Wno-sign-compare -DIPV6 -g -O2 -MT fping-socket4.o -MD -MP -MF .deps/fping-socket4.Tpo -c -o fping-socket4.o `test -f 'socket4.c' || echo './'`socket4.c
mv -f .deps/fping-socket4.Tpo .deps/fping-socket4.Po
gcc -DHAVE_CONFIG_H -I. -I..    -Wall -Wextra -Wno-sign-compare -DIPV6 -g -O2 -MT fping-optparse.o -MD -MP -MF .deps/fping-optparse.Tpo -c -o fping-optparse.o `test -f 'optparse.c' || echo './'`optparse.c
mv -f .deps/fping-optparse.Tpo .deps/fping-optparse.Po
gcc -DHAVE_CONFIG_H -I. -I..    -Wall -Wextra -Wno-sign-compare -DIPV6 -g -O2 -MT fping-socket6.o -MD -MP -MF .deps/fping-socket6.Tpo -c -o fping-socket6.o `test -f 'socket6.c' || echo './'`socket6.c
mv -f .deps/fping-socket6.Tpo .deps/fping-socket6.Po
gcc -Wall -Wextra -Wno-sign-compare -DIPV6 -g -O2   -o fping fping-fping.o fping-seqmap.o fping-socket4.o fping-optparse.o fping-socket6.o
make[2]: Leaving directory '/home/cacti/fping/src'
make[2]: Entering directory '/home/cacti/fping'
make[2]: Leaving directory '/home/cacti/fping'
make[1]: Leaving directory '/home/cacti/fping'
Making install in doc
make[1]: Entering directory '/home/cacti/fping/doc'
make[2]: Entering directory '/home/cacti/fping/doc'
make[2]: Nothing to be done for 'install-exec-am'.
 /usr/bin/mkdir -p '/usr/share/man/man8'
 /usr/bin/install -c -m 644 fping.8 '/usr/share/man/man8'
make[2]: Leaving directory '/home/cacti/fping/doc'
make[1]: Leaving directory '/home/cacti/fping/doc'
Making install in src
make[1]: Entering directory '/home/cacti/fping/src'
make[2]: Entering directory '/home/cacti/fping/src'
 /usr/bin/mkdir -p '/usr/sbin'
  /usr/bin/install -c fping '/usr/sbin'
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/home/cacti/fping/src'
make[1]: Leaving directory '/home/cacti/fping/src'
make[1]: Entering directory '/home/cacti/fping'
make[2]: Entering directory '/home/cacti/fping'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/home/cacti/fping'
make[1]: Leaving directory '/home/cacti/fping'
::: Fixing file permissions...
::: Beginning SmokePing install...
::: Installing required  packages...
::: Uh-oh. Sorry, unsupported OS Exiting...

**Comment by KnoAll** [comment]
I've not tried installing smokeping on alma/rocky so the scripts are not updated yet. I'll have to take a look and see what is going on. could take a bit.

**Comment by Schietb** [comment]
OK, thank you very much.
I'll stay tuned waiting for the script update.

**Comment by KnoAll** [comment]
Having to make some pretty significant updates for install to work on Alma/Rocky. Stay tuned.

**Comment by Schietb** [comment]
Thank you so much.

Also another detail, nothing to do with SmokePing install :

I just migrated my cacti installation to a brand new server, but was unable to backup the original cacti using cacti-upgrade --backup-data because there are 17,7G of rrd files and there was not enough space on the /home partition to store the backup file...
Nevertheless, I downloaded your backup-cacti.sh and restore-cacti.sh scripts, modifed them to use the /tmp instead of /home/cacti, and used them indepedently to backup the old server content and restore it to the new one.
It worked finally very fine, but it would be great and very useful if your script was asking where to store/find the backup file ;)

**Comment by KnoAll** [comment]
Good point. should be able to have a prompt to stipulate storage path.

**Comment by KnoAll** [comment]
OK, I think I have the smokeping install working now. Took reworking for Alma/Rocky in a number of areas. I'm doing a bit of testing before I push it to the main branch.

**Comment by KnoAll** [comment]
OK, after as much testing as I could do I've pushed the changes to the main branch, you can try it again. Let me know how it goes.

**Comment by Schietb** [comment]
Sorry for the late feedback.
I just tested, and it works fine.
Thanks a lot.
