### ISSUE TITLE
newly created graphs are not populating

### ISSUE THREAD

**Issue by KnoAll** [KnoAll/cacti-template#42]
rrd for newly created graphs are not being written by the poller

**Comment by KnoAll** [comment]
made an adjustment to the update script

**Comment by fastsui** [comment]
Hi,
After Updateing on the newest Version i see on the new Graph this Message 👍 
https://i.imgur.com/vx43hF1.png

Do you have any Inputs what is the problem ?

**Comment by KnoAll** [comment]
You could try running this and see if it helps...
bash <(curl -s https://raw.githubusercontent.com/KnoAll/cacti-template/master/update-permissions.sh)

**Comment by fastsui** [comment]
@KnoAll 
Thanks a lot! Its works. Also thank you for the great job that you have do here ;)

**Comment by fastsui** [comment]
its works. thanks a lot

**Comment by KnoAll** [comment]
Glad to hear it. I have a new feature staged in dev that will allow --fix-permissions on the cacti-upgrade.sh script.
