### ISSUE TITLE
alto processamento CPU

### ISSUE THREAD

**Issue by RodrigoMato** [KnoAll/cacti-template#54]
Olá não tenho muita expertise em linux, eu instalei uma VM disponibilizada por vocês é otima!! o meu problema é que tenho duas placas de rede sendo uma virada para a publica e a outra para a rede onde quero monitorar meus devices quando habilito a interface ens33 o processamento da CPu sobe muito na outra interface isso não ocorre? será que existe algum processo que devo fazer.

desde já agradeço.

**Comment by KnoAll** [comment]
I do not think I can help with that. That does not seem to be related to Cacti. That seems to be an advanced Linux configuration that I am not familiar with.  I suggest farther web searches specifically for Linux/CentOS.  Sorry I cannot be more help.
