### ISSUE TITLE
Cacti graph permissions issue

### ISSUE THREAD

**Issue by rkrasovich** [KnoAll/cacti-template#62]
I am a network engineer, but weal at linix.
Have an issue with generation graphs. I found that the /var/www/html/cacti/rra has the 3 4 5.. directories.
The 3 directory, which has the local cacti graphs had cacti apache rights.
The new directories have apache apache 4 5 ....
I used cmod 777 on the other directories and now graphs are being generated.

Is this the right way to fix problem, or is there another solution?

**Comment by KnoAll** [comment]
I'm still trying to work through the exact permissions cacti and apache need. i have a short term fix you can use to update them though. After you have updated to 1.2.3 you can do
./cacti-upgrade.sh --fix-permissions

Let me know if that helps.

**Comment by rkrasovich** [comment]
Thanks for getting back to me!
Do you have an OVA 1.2.3 version? Or do I do a manual upgrade to 1.2.3.

I also do not see the "upgrade script (v1.2.2 is out now)". Perhaps I am looking in the wrong place.

Thanks again for your help.
Rich K.

PS is the paypal link on your blog for your personal account??

**Comment by KnoAll** [comment]
Yes, you can run the upgrade to 1.2.3 directly. (no need to go to 1.2.3 first)
from the cacti home directory do
./cacti-upgrade.sh
the upgrade will also fix the permissions issue for the files that are already created.

Yes that is my personal

**Comment by rkrasovich** [comment]
OK thanks for your help.

**Comment by KnoAll** [comment]
try re-running the script with --fix-permissions
