### ISSUE TITLE
I can not config the IP address 

### ISSUE THREAD

**Issue by nuccave** [KnoAll/cacti-template#72]
![image](https://user-images.githubusercontent.com/58420776/69947218-c9153080-151f-11ea-9383-11da180147da.png)

**Comment by KnoAll** [comment]
The template network is set to DHCP, it appears that the networking is not connected or DHCP is not available?

**Comment by nuccave** [comment]
How can I set the static IP Sir ?

**Comment by nuccave** [comment]
and i had the trouble with the graphs like this

**Comment by nuccave** [comment]
![image](https://user-images.githubusercontent.com/58420776/70120698-c17c9580-169f-11ea-8abd-f232db2b89b5.png)

**Comment by nuccave** [comment]
![image](https://user-images.githubusercontent.com/58420776/70120752-db1ddd00-169f-11ea-8437-c38cfd05d319.png)

**Comment by KnoAll** [comment]
This is a standard install of CentOS7. You can follow this guide for setting a static IP.
https://www.techrepublic.com/article/how-to-configure-a-static-ip-address-in-centos-7/

**Comment by KnoAll** [comment]
As for the graphs, you may need to run the script with --fix-permissions switch.

**Comment by nuccave** [comment]
thank you! i will do as your guide
