### ISSUE TITLE
Permissions issue for /var/www/html/cacti/rra directories.

### ISSUE THREAD

**Issue by jspugs** [KnoAll/cacti-template#74]
Running your [Update 12/10/2019] version. Hit errors for permissions on the rra directory.

Here's the logs from cacti:
2019/12/19 06:38:56 - CMDPHP ERROR: Unable to set directory permissions for '/var/www/html/cacti/rra/5'
--
2019/12/19 06:38:56 - CMDPHP PHP ERROR WARNING Backtrace: (/host.php[60]:form_save(), /host.php[252]:api_device_save(), /lib/api_device.php[793]:chown(), CactiErrorHandler())
2019/12/19 06:38:56 - ERROR PHP WARNING: chown(): Operation not permitted in file: /var/www/html/cacti/lib/api_device.php on line: 793

Resolved by changing permissions on the rra folder:

[root@cactitemplate cacti]# chown -R cacti.apache /var/www/html/cacti/rra/
[root@cactitemplate cacti]# chmod -R 775 /var/www/html/cacti/rra/
[root@cactitemplate cacti]# chmod g+s /var/www/html/cacti/rra/

This problem reproduces every time you create a new device.

You can also work around this in Cacti by changing the setting 'Structured RRD Paths' to off.  This works around the issue, by not creating new directories for each device. This is ultimately how I resolved the issue going forward.

Might be worth making a small tweak to your appliance by turning off that feature.  I appreciate your efforts to put this together and make it available for folks!

**Comment by KnoAll** [comment]
Thats a good idea, I think I will put that in place. It should make things easier moving forward. 

You can also run the upgrade script with switch --fix-permissions and it will reset everything.
