### ISSUE TITLE
Cacti upgrade from 1.1.38 to 1.2.9 is not completed

### ISSUE THREAD

**Issue by rrgg-it** [KnoAll/cacti-template#89]
Hello,
I need help because I upgrade my cacti based on CentOS 7 from 1.1.38 to 1.2.9 by your script, the update seems to end correctly but when I log in to cacti home page, the procedure for completing the update does not start and cacti remains at the version 1.1.38; in detail:
I point my web browser to http://my-server/cacti/ but I don't see any instructions, it only ask to me credential to login, I insert credentials and it starts to show to me the graph as always happen, version remain 1.1.38.

**Comment by KnoAll** [comment]
It would appear the upgrade did not complete. have you tried it again?

**Comment by rrgg-it** [comment]
Yes I try again but result is the same, I try to update another host but also in this case the result is the same: all seems to work fine but at he end when I Login it show to me the graphs...

**Comment by KnoAll** [comment]
are there any messages or errors while running the script? what OS are you on?
please send a list of the files in your home directory

**Comment by rrgg-it** [comment]
No, no particoular message and no errors while running the script,
OS is Centos 7, actually installation is your old 1.1.38 OVF file.
In home directory I found only cacti folder, no files are present but actually Cacti runs based on revert to the snapshot captured before the update. 
![image](https://user-images.githubusercontent.com/61889248/76363782-07429d00-6324-11ea-9256-9663050f7f30.png)

**Comment by KnoAll** [comment]
All of these scripts are intended to be run from the command line only. If you are not running from there that could explain the issue

**Comment by rrgg-it** [comment]
Sorry for delay...
I run scripts manually directly to cli!
