### ISSUE TITLE
Problems with OVA download

### ISSUE THREAD

**Issue by mrfixit100** [KnoAll/cacti-template#91]
I'm having a problem downloading and extracting the OVA from the RAR.  Is there a known issue with the current RAR file?  I've tried downloading several times from multiple locations.

**Comment by KnoAll** [comment]
Not that I have been made aware of. I'll try it to verify

**Comment by KnoAll** [comment]
I just downloaded from the website, expanded it, and loaded it into VirtualBox with no issues. Where are you running into trouble?
