### ISSUE TITLE
routerconfigs and PHPTelnet

### ISSUE THREAD

**Issue by Cronist** [KnoAll/cacti-template#92]
do we have anything to do to solve this error?
Cacti 1.2.10
Linux cactitemplate.local 3.10.0-693.17.1.el7.x86_64 #1 SMP Thu Jan 25 20:13:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
PHP 7.1.33 (cli) (built: Mar 17 2020 09:14:41) ( NTS )

2020/04/02 02:00:22 - CMDPHP PHP ERROR Backtrace: (/plugins/routerconfigs/router-devices.php[30]:include_once(), /plugins/routerconfigs/router-devices.php[30]:CactiErrorHandler())
--
2020/04/02 02:00:22 - ERROR PHP DEPRECATED in Plugin 'routerconfigs': Methods with the same name as their class will not be constructors in a future version of PHP; PHPTelnet has a deprecated constructor in file: /var/www/html/cacti/plugins/routerconfigs/functions.php on line: 801

best regards.

**Comment by KnoAll** [comment]
I believe you will need to go through the Cacti.net forums to get support on that plugin.
