### ISSUE TITLE
Any manual or help to connect to PaloAlto firewall?

### ISSUE THREAD

**Issue by bushtor** [KnoAll/cacti-template#96]
Hi,
I have located the Palo Alto template within the OVA but I don't know how to connect so I have the FW's interfaces listed...   Thanks a lot for a link or any help on this.
regards Tor

**Comment by KnoAll** [comment]
I have a PA connected with Cacti today. What is the issue that you are having? You must enable SNMP on the PA under Device > Setup > Operations > Miscellaneous and have the appropriate SNMP Community String
