### ISSUE TITLE
Cacti OVA no Work.

### ISSUE THREAD

**Issue by komatsu002** [KnoAll/cacti-template#99]
Hello friends:

today download this CentOS7 Appliance with v1.2.8 Cacti, OVA is ~ 2.4g I have installed it on my ESXI and everything is fine with centos 7, but cacti does not work I go to http: // My-Server-IP / cacti and it does not open cacti . I have internet and it is not a network problem. Any ideas what happens?

**Comment by KnoAll** [comment]
what result do you get? what happens if go browse without the /cacti?

**Comment by komatsu002** [comment]
Hello KnoAll:
Apache is running since I get the test message 123. When I put / cacti, nothing happens, it does not open the CACTI home page. I already checked all the services, Mariadb, Httpd and Snmpd and they are all running. Any ideas?

Thank you.

**Comment by komatsu002** [comment]
Hello KnoAll:
I made a new installation in a centos 7 just installed using your KnoAll / cacti-template and Cacti is working correctly. Thank you for your contributions.
